flatpak install  --user "com.bitwarden.desktop" 
flatpak install  --user "com.discordapp.Discord" 
flatpak install  --user "com.spotify.Client" 
flatpak install  --user "org.onlyoffice.desktopeditors" 
flatpak install  --user "org.telegram.desktop" 
