on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Run
        shell: bash

        run: |
          echo "running on $PWD"
          ./local/bin/setup.sh

        env:
          DOTFILES_REF: ${{github.sha}}
          REPO: ${{github.workspace}}
