on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Run Setup Script
        run: |
          chmod +x ./.local/bin/setup.sh
          ./.local/bin/setup.sh
        shell: bash
